docs_dir: docs

# Project information
site_name: IsardVDI Technical docs
site_url: http://thedocs.isardvdi.com
site_description: IsardVDI Technical & Practical info (Escola del Treball Barcelona)
site_author: IsardVDI

# Repository
repo_name: 'isard-vdi/thedocs'
repo_url: https://github.com/isard-vdi/thedocs

# TOC
pages:
- Introduction: index.md
- Storage:
    - Concepts: storage/concepts.md
    - Tools: storage/tools.md
    - Raid: storage/raid.md
    - DRBD: storage/drbd.md
    - Cache: 
       - EiO: storage/cache/eio.md
       - Writeboost: storage/cache/writeboost.md
- Networking:
    - Concepts: networking/concepts.md
    - Tools: networking/tools.md
    - Bondings: networking/bondings.md
    - TenGigabit: networking/10g.md
    - FortyGigabit: networking/40g.md
- Clusters & HA:
    - Pacemaker: clusters/pacemaker.md
    - Stonith: clusters/stonith.md
    - OCF resources: 
       - EnhanceIO: clusters/ocf/eio.md
       - Writeboost: clusters/ocf/writeboost.md
- Virtualization:
    - Concepts: virtualization/concepts.md
    - Disk images: virtualization/disks.md
    - GPUs: virtualization/gpus.md
- Setups:
    - HA Clusters:
       - Active-Pasive: setups/ha/active_passive.md
       - Active-Active: setups/ha/active_active.md
    - Virtualization:
        - GPU SRIOV: setups/virtualization/gpu_sriov.md
- Utilities:
    - Monitoring: utilities/monitoring.md
    - Grafana: utilities/grafana.md
    - fio: utilities/fio.md
- About: about/license.md

# Copyright
copyright: Copyright &copy; 2018 <a href="http://www.isardvdi.com">IsardVDI</a>.

# Documentation and theme
theme:
  name: 'material'
  palette:
    primary: 'orange'
    accent: 'blue'
  logo: 'images/logo.svg'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'

# Extensions
markdown_extensions:
  - admonition
  - codehilite(guess_lang=false)
  - toc(permalink=true)
